// <auto-generated />
using System;
using EVoucherManagementSystem.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EVoucherManagementSystem.Migrations
{
    [DbContext(typeof(DataContext))]
    partial class DataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("EVoucherManagementSystem.Models.BuyTypesModel", b =>
                {
                    b.Property<string>("id")
                        .HasColumnType("char(37)");

                    b.Property<DateTime>("createdDateTime")
                        .HasColumnType("datetime");

                    b.Property<int>("eVoucher_maxlimit")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<int>("giftUser_maxlimit")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<int>("isGiftOthers")
                        .HasColumnType("int");

                    b.Property<int>("isMyself")
                        .HasColumnType("int");

                    b.Property<DateTime?>("updatedDateTime")
                        .HasColumnType("datetime");

                    b.HasKey("id")
                        .HasName("PK_BuyTypes");

                    b.ToTable("BuyTypes", (string)null);
                });

            modelBuilder.Entity("EVoucherManagementSystem.Models.EVouchersModel", b =>
                {
                    b.Property<string>("id")
                        .HasColumnType("char(37)");

                    b.Property<int>("amount")
                        .HasColumnType("int");

                    b.Property<DateTime>("createdDateTime")
                        .HasColumnType("datetime");

                    b.Property<string>("description")
                        .IsRequired()
                        .HasColumnType("nvarchar(1000)");

                    b.Property<DateTime>("expiryDate")
                        .HasColumnType("datetime");

                    b.Property<string>("image")
                        .IsRequired()
                        .HasColumnType("nvarchar(300)");

                    b.Property<int>("isActive")
                        .HasColumnType("int");

                    b.Property<string>("phoneNo")
                        .IsRequired()
                        .HasColumnType("nvarchar(25)");

                    b.Property<string>("qrCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(300)");

                    b.Property<int>("quantity")
                        .HasColumnType("int");

                    b.Property<string>("title")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("updatedDateTime")
                        .HasColumnType("datetime");

                    b.Property<string>("userName")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("user_id")
                        .IsRequired()
                        .HasColumnType("char(37)");

                    b.HasKey("id")
                        .HasName("PK_EVouchers");

                    b.ToTable("EVouchers", (string)null);
                });

            modelBuilder.Entity("EVoucherManagementSystem.Models.ItemPurchaseModel", b =>
                {
                    b.Property<string>("id")
                        .HasColumnType("char(37)");

                    b.Property<DateTime>("createdDateTime")
                        .HasColumnType("datetime");

                    b.Property<string>("item")
                        .IsRequired()
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("promocode")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.Property<int>("totalamount")
                        .HasColumnType("int");

                    b.Property<DateTime?>("updatedDateTime")
                        .HasColumnType("datetime");

                    b.Property<string>("userid")
                        .HasColumnType("longtext");

                    b.HasKey("id")
                        .HasName("PK_ItemPurchase");

                    b.ToTable("ItemPurchase", (string)null);
                });

            modelBuilder.Entity("EVoucherManagementSystem.Models.PaymentMethodsModel", b =>
                {
                    b.Property<string>("id")
                        .HasColumnType("char(37)");

                    b.Property<DateTime>("createdDateTime")
                        .HasColumnType("datetime");

                    b.Property<int>("discountPercent")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("updatedDateTime")
                        .HasColumnType("datetime");

                    b.HasKey("id")
                        .HasName("PK_PaymentMethods");

                    b.ToTable("PaymentMethods", (string)null);
                });

            modelBuilder.Entity("EVoucherManagementSystem.Models.PurchaseEVouchersModel", b =>
                {
                    b.Property<string>("id")
                        .HasColumnType("char(37)");

                    b.Property<string>("buyType_id")
                        .IsRequired()
                        .HasColumnType("char(37)");

                    b.Property<DateTime>("createdDateTime")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("eVoucher_id")
                        .IsRequired()
                        .HasColumnType("char(37)");

                    b.Property<int>("isUsed")
                        .HasColumnType("int");

                    b.Property<int>("netAmount")
                        .HasColumnType("int");

                    b.Property<string>("paymentMethod_id")
                        .IsRequired()
                        .HasColumnType("char(37)");

                    b.Property<string>("promoCode")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.Property<DateTime?>("updatedDateTime")
                        .HasColumnType("datetime(6)");

                    b.HasKey("id")
                        .HasName("PK_PurchaseEVouchers");

                    b.ToTable("PurchaseEVouchers", (string)null);
                });

            modelBuilder.Entity("EVoucherManagementSystem.Models.UsersModel", b =>
                {
                    b.Property<string>("id")
                        .HasColumnType("char(37)");

                    b.Property<DateTime>("createdDateTime")
                        .HasColumnType("datetime");

                    b.Property<string>("password")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("phoneNo")
                        .IsRequired()
                        .HasColumnType("nvarchar(25)");

                    b.Property<DateTime?>("updatedDateTime")
                        .HasColumnType("datetime");

                    b.Property<string>("userName")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("id")
                        .HasName("PK_Users");

                    b.ToTable("Users", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
